### PR TITLE
Add --s3-use-sigv4 and --s3-endpoint options

### LINKED ISSUE #101: Add option to use AWS Signature Version 4/support for new AWS locations
Newer AWS locations (in my case Frankfurt) will only authenticate clients that use AWS Signature Version 4. It would be nice to have it as an option, because these newer locations are unusable otherwise. SigV4 seems to require an explicit S3 host parameter so this would have to be added as a command line option, too. My suggestion is to introduce a `--s3-host` flag. If set, SigV4 should automatically be used. Alternatively a new `--s3-sigv4` flag could be used to make this more explicit.

It seems that older locations all support SigV4 so it should not be a problem to be compatible with those. Maybe users of these older locations will benefit from SigV4 as well as it promises to provide increased security and performance, but I didn't research that any further. I am just trying to get this to work with an S3 bucket in Frankfurt.

Apparently, enabling SigV4 with boto requires two changes. First, you need to set `os.environ['S3_USE_SIGV4'] = 'True`. Second, you need to set the host parameter when calling `S3Connection()`, or `boto.connect_s3()`, respectively. Also see https://github.com/boto/boto/issues/2741

I'm a complete Python noob so I may not be the most suitable person to make a PR for this, but I can give it a try if no one else has the time.

### PR DESCRIPTION
**Pull request by padde**
Fixes #101

I had a look into the source code and what I needed didn't look to hard to implement, so I went ahead and did it myself.

Any suggestions are welcome. As I said I haven't got any experience with Python, please be forgiving :wink:.

### CODE REVIEW

**Comment by padde** [comment]
@danilop have you had a chance to take a look at this yet? Thanks.

**Comment by marek-obuchowicz** [comment]
Please please release it to pip repository. At the moment sig v4 is required in eu-central-1 and we can't use it without without this feature.

It would be also nice to have default value for s3 endpoint set to 's3.amazonaws.com' - but it's nice to have. But this PR is very very important to be released :)

**Comment by bitsofinfo** [comment]
@padde please update the README for these new options

**Comment by padde** [comment]
@bitsofinfo yeah that would be a good idea, I'll make a PR. Honestly with this PR I first wanted to see if I'm heading in the right direction, didn't think it would be merged as is.

**Comment by dzinek** [comment]
Please release it as 2.3.3 and push to the pip repository.

We would like to use it, but we cannot relay on the master branch and  have to install it from pip with fixed version.

**Pull request merged**
