### PR TITLE
An attempt at splitting __init__'s classes into their own files

### PR DESCRIPTION
**Pull request by Liath**
Per https://github.com/danilop/yas3fs/issues/123

I split all classes into their own files for the most part except for like LinkedList being in FSCache since that's the only place it is used.

I thought about maybe putting all the FS stuff in a folder to group it up. Which would switch the imports as going from:
```
from .FSCache import FSCache
from .FSData import FSData
from .FSRange import FSRange
from .PartOfFSData import PartOfFSData
```
To:
```
from .fs import FSCache, FSData, FSRange, PartOfFSData
```
Idk, I'm not really sure how to structure a python project.

### CODE REVIEW

**Comment by Liath** [comment]
I added a skeleton for unit tests too. I'll try to get basic functionality coverage in for every in another PR.

**Comment by Liath** [comment]
Just noticed this had a waiting conflict /shrug
Should be good now :)

**Comment by jazzl0ver** [comment]
Yeah, looks like you were working with the old code and now requested to merge that old code with the current one.
For example, your version of code:
```
__init.py__:139
    parser.add_argument('--cache-path', metavar='PATH', default='',
help='local path to use for disk cache (default is /tmp/yas3fs/BUCKET/PATH)')
```
The latest version is:
```
__init.py__:3229
    parser.add_argument('--cache-path', metavar='PATH', default='',
help='local path to use for disk cache (default is /tmp/yas3fs-BUCKET-PATH-random)')
```
And this does not seem to be the only difference.

Do I understand it incorrectly?

**Comment by Liath** [comment]
Ah, must have messed up a merge. I can recreate from latest. I don't think there were that many differences.

**Comment by jazzl0ver** [comment]
There were a lot of differences! Thanks!

**Pull request closed without merging**
